// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package robot.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
//import robot.subsystems.*;
//import robot.Robot;
//import robot.Robot;

/**
 *
 */
public class Goto_Retreive_Cargo_Floor_Pos_CmdGrp extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public Goto_Retreive_Cargo_Floor_Pos_CmdGrp() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 
        // Set Current Robot State Indicator
        addSequential(new Set_Robot_Pos_Cmd("CargoFloor"));


        // 1. Manipulator Selector to Cargo Position
        // 2. Elev to Floor
        // 3. Intake Roller to retract
        // 4. Intake to Extend

        // 5. Cargo capture CmdGrp  (This blocks till ball is captured

        // ------------------------ 1. Manipulator to Cargo Position ---------------------------
        // -------------------------------------------------------------------------------------
        addSequential (new Mani_SelectorValve_Set_Cmd("Cargo"));

        // --------------------------- 2. Move Elevator to BOTTOM ------------------------------
        // -------------------------------------------------------------------------------------
        //                ElevToPosCmd( position, distance, holdMode, timeOut)
        addParallel(new   ElevToPosCmd( "Bottom",    0.0,     0,       3.5));

        // -------------------------- 3. Intake Roller to Retract Speed ------------------------
        // -------------------------------------------------------------------------------------
        //                Intake_To_Pos_Cmd(String position, boolean waitMode, double timeout));
        addSequential(new Intake_RollerMotor_Set_Cmd( "Retract" ));
        
        // ----------------------------4.  Extend Intake Roller --------------------------------
        // -------------------------------------------------------------------------------------
        //                Intake_To_Pos_Cmd(String position, boolean waitMode, double timeout));
        addSequential(new Intake_To_Pos_Cmd(   "Extended",            true,              3.0));

        // ------------------------ 5. Cargo Capture Ball Cmd (This blocks) --------------------
        // -------------------------------------------------------------------------------------
        addSequential (new Cargo_Capture_CmdGrp());

    } 
}
